# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('agents', ['core'])
    module.source = [
        'model/wrapper.cc',
        'helper/agents-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('agents')
    module_test.source = [
        'test/agents-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'agents'
    headers.source = [
        'model/wrapper.h',
        'helper/agents-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    if bld.env['ENABLE_JNI']:
        module.use.extend(['JNI'])
        module_test.use.extend(['JNI'])

    # bld.ns3_python_bindings()

